// Importing Google Fonts using Next.js built-in font optimization
import { Outfit, Ovo } from "next/font/google";

// Importing global CSS styles for the whole app
import "./globals.css";

// Configure Outfit font with specific subsets and weights
const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // multiple font weights
});

// Configure Ovo font (only regular weight)
const ovo = Ovo({
  subsets: ["latin"],
  weight: ["400"],
});

// Metadata for the application (used by Next.js for SEO)
export const metadata = {
  title: "Portfolio - Neluni Wijayasekara",
  description: "Generated by create next app",
};

// Root layout component wraps the entire application
// Every page will be rendered inside this layout
export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth ">
      <body
        // Apply both fonts, enable antialiasing, set line-height, and hide horizontal overflow
        className={`${outfit.className} ${ovo.className} antialiased leading-8 overflow-x-hidden`}
      >
        {children} {/* Render all child components/pages here */}
      </body>
    </html>
  );
}
